//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int id { get; set; }
        public int playerId1 { get; set; }
        public int playerId2 { get; set; }
        public string boardLayout { get; set; }
    
        public virtual Usr Usr { get; set; }
        public virtual Usr Usr1 { get; set; }
    }
}
